### ISSUE TITLE
iOS9.0视频预览,点完成会crash

### ISSUE THREAD

**Issue by JackyL90** [SilenceLove/HXPhotoPicker#350]
iOS9.0，选取视频，视频预览后，再点完成，会crash，demo也有这问题

**Comment by Toga21** [comment]
iOS10.3.2也会出现这个问题

Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x174018ec0 of class AVPlayerItem was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x174436a60> (
<NSKeyValueObservance 0x170855060: Observer: 0x10ef8b380, Key path: status, Options: <New: YES, Old: YES, Prior: NO> Context: 0x0, Property: 0x17085b7b0>
<NSKeyValueObservance 0x17464f330: Observer: 0x10ef8b380, Key path: loadedTimeRanges, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x174245580>
<NSKeyValueObservance 0x174243b70: Observer: 0x10ef8b380, Key path: playbackBufferEmpty, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x174054310>
<NSKeyValueObservance 0x1708593b0: Observer: 0x10ef8b380, Key path: playbackLikelyToKeepUp, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x17424b9d0>
)'
