### ISSUE TITLE
Edited Result

### ISSUE THREAD

**Issue by bhadresh13** [SilenceLove/HXPhotoPicker#720]
In edit Photo 

i apply crop and Nashville filter on Image and store data 
afterward i remove  Nashville filter , it also remove crop data also 

how to get crop data with result

**Comment by SilenceLove** [comment]
How do you delete the filter? What is the code?

**Comment by bhadresh13** [comment]
After applying multiple filters and adjust (filter edit) effect like brightness, sharpen etc and then crop on a single image url then I found one issue . The issue occurs is when all the filters and adjust effects are gone then in that scenario the crop filter is automatically nil inside the edited result object 

Can you please guide us how to deal with it and create the similar function just like Apple default library works so that cropping data won’t effected 

Please have a look on attached video for your reference 



https://github.com/user-attachments/assets/f72abe23-2a94-4467-ab0c-e6488907b427

**Comment by SilenceLove** [comment]
This seems to be a bug in the previous version, try the latest version. It has been fixed

发自我的iPhone


------------------ Original ------------------
From: Bhadresh Sonani ***@***.***&gt;
Date: Mon,Aug 12,2024 5:23 PM
To: SilenceLove/HXPhotoPicker ***@***.***&gt;
Cc: Silence ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [SilenceLove/HXPhotoPicker] Edited Result (Issue #720)





 
After applying multiple filters and adjust (filter edit) effect like brightness, sharpen etc and then crop on a single image url then I found one issue . The issue occurs is when all the filters and adjust effects are gone then in that scenario the crop filter is automatically nil inside the edited result object
 
Can you please guide us how to deal with it and create the similar function just like Apple default library works so that cropping data won’t effected
 
Please have a look on attached video for your reference
 
https://github.com/user-attachments/assets/f72abe23-2a94-4467-ab0c-e6488907b427
